### ISSUE TITLE
JavaScript (p5js) Examples TODO

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/HCID521Wi2020#2]
Some potential TODOs for p5js examples to show in class.

**Basic Game Examples**
- [ ] Bring flappy bird into github
- [ ] Bring Snakes into github
- [x] Make a two-player pong? Probably a good idea to demo w, a, s, d mapping and up, down, left, right mapping
- [ ] Make a basic side scroller demo?
- [ ] Make basic scene generator?
- [ ] Make the old Atari joust game (back and forth input plus flapping (spacebar)). https://en.wikipedia.org/wiki/Joust_(video_game)

**Body and Sound Input Demos**
- [ ] **Sound**: Bring FFT playground over from p5js editor (https://editor.p5js.org/jonfroehlich/present/3J-uyZ8O6) and make a game version (try to get the ball into a hole or basket?)
- [ ] **Sound**: make scrolling landscapes based on fft
- [ ] **Video (PoseNet)**: Make a game version. Maybe bounce ball off of the nose?
- [ ] **Video (PoseNet)**: Make basic bubble popping game, like: https://youtu.be/iRH2ny9qsFc?t=83 or https://scratch.mit.edu/projects/39439644/

**Input Control Demos**
- [ ] **Sound**: Use pitch to control left, right, up, and down (for games like Snake)
- [ ] **Sound**: Use sound amplitude (one dimensional input) to control flappy bird
- [ ] **Video**: break screen into a quadrant. Depending on where there is the *most* movement in the four quadrants, map to left, right, up, and down
